/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Order */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        address?: string;
                        /** Format: email */
                        email?: string;
                        items?: string[];
                        payment?: string;
                        /** Format: utc-millisec */
                        phone?: string;
                        total?: number;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        "Access-Control-Allow-Origin"?: string;
                        Connection?: string;
                        "Content-Length"?: number;
                        Date?: string;
                        ETag?: string;
                        "Keep-Alive"?: string;
                        "X-Powered-By"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            total?: number;
                        };
                    };
                };
                /** @description Product not found */
                400: {
                    headers: {
                        "Access-Control-Allow-Origin"?: string;
                        Connection?: string;
                        "Content-Length"?: number;
                        Date?: string;
                        ETag?: string;
                        "Keep-Alive"?: string;
                        "X-Powered-By"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product List */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        "Access-Control-Allow-Origin"?: string;
                        Connection?: string;
                        "Content-Length"?: number;
                        Date?: string;
                        ETag?: string;
                        "Keep-Alive"?: string;
                        "X-Powered-By"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                category?: string;
                                description?: string;
                                id?: string;
                                image?: string;
                                price?: number;
                                title?: string;
                            }[];
                            total?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/854cef69-976d-4c2a-a18c-2aa45046c390": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Item */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        "Access-Control-Allow-Origin"?: string;
                        Connection?: string;
                        "Content-Length"?: number;
                        Date?: string;
                        ETag?: string;
                        "Keep-Alive"?: string;
                        "X-Powered-By"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            category?: string;
                            description?: string;
                            id?: string;
                            image?: string;
                            price?: number;
                            title?: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        "Access-Control-Allow-Origin"?: string;
                        Connection?: string;
                        "Content-Length"?: number;
                        Date?: string;
                        ETag?: string;
                        "Keep-Alive"?: string;
                        "X-Powered-By"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
